# download our files
git clone https://github.com/lindenb/makefile2graph.git
# create directory
mkdir mymakefile2graph
# enter directory
cd mymakefile2graph
# run make command
make -C makefile2graph/.
# install graphviz
apt-get update && apt-get install -y graphviz
